added limitations and scenarios
k8-proxy/k8-proxy-documentation pull request #134
Opened 2021-06-01 15:48 UTC by svf97

2021-06-01 15:52 UTC, GINAGC commented
@svf97 you are sending limitations to the python file, please remove. We don't need to add the limitations here.

2021-06-01 15:52 UTC, GINAGC requested changes
limitations need to be removed

2021-06-01 16:41 UTC, svf97 commented
https://github.com/k8-proxy/cs-k8s-api/issues/182
We don't need it anymore?

2021-06-02 17:45 UTC, GINAGC approved these changes

2021-06-02 17:45 UTC, merged